webtalk_init -webtalk_dir C:/FPGAPrj/VIVADO/PIPELINE/PIPELINE.sim/sim_1/behav/xsim.dir/PIPELINE_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 18 14:46:27 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1368829" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211101165_1777512702_210617328_901" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "903c64c5-9302-4149-b535-7193d14dbe02" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c1c93375afed4e18a1b126f1fbeb919e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "27" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "20" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "127 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "62 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "2257" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2555" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "486" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.39_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "36544_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3916474593 -regid "211101165_1777512702_210617328_901" -xml C:/FPGAPrj/VIVADO/PIPELINE/PIPELINE.sim/sim_1/behav/xsim.dir/PIPELINE_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/FPGAPrj/VIVADO/PIPELINE/PIPELINE.sim/sim_1/behav/xsim.dir/PIPELINE_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/FPGAPrj/VIVADO/PIPELINE/PIPELINE.sim/sim_1/behav/xsim.dir/PIPELINE_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
